Customer History text added
Software-Lifecycle-Consultants/slc-open-hms pull request #462
Opened 2024-06-18 12:12 UTC by Kasunkule

2024-06-19 07:41 UTC, iamarasekera approved these changes

2024-06-19 07:47 UTC, iamarasekera requested changes
@Kasunkule Please check the responsiveness and confirm.

2024-06-19 07:50 UTC, Kasunkule commented
I checked the responsiveness. No issue.

2024-06-20 02:13 UTC, iamarasekera commented
@Kasunkule please attach the relevant dev task/bug to this PR.

2024-06-20 06:28 UTC, merged